export enum ActionTypes {
  ADD_EXCHANGE = "ADD_EXCHANGE",
  ADD_TO_BY_EID = "ADD_TO_CURRENCY_BY_EXCHANGEID",
  REMOVE_TO_BY_CID_AND_EID = "REMOVE_TO_CURRENCY_BY_CURRENCYID_AND_EXCHANGEID",
  EDIT_TO_CODE_BY_CID_AND_EID = "EDIT_TO_CURRENCY_CODE_BY_CURRENCYID_AND_EXCHANGEID",
  EDIT_FROM_CODE_BY_EID = "EDIT_FROM_CURRENCY_CODE_BY_EXCHANGEID",
  EDIT_FROM_VALUE_BY_EID = "EDIT_FROM_CURRENCY_VALUE_BY_EXCHANGEID",
}
